### ISSUE TITLE
k8s executor should be able to create PVCs on demand when submitting pods

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1227]
## Usage scenario 

Now that I'm able to run some large workflows in k8s thanks to nextflow, one thing that I'd like to do is to provide ample local storage to worker pods and enable `scratch` so that I can run many pods without overwhelming the shared storage volume.

I see that the `pod` directive currently allows you to attach an existing PVC to the worker pod, but I'm not sure how useful that is. I could provision a PVC before launching the workflow, but only one process would be able to use it at a time. I could try to provision many PVCs according to how many pods I expect will run in parallel, but then I have to do something like memory management with PVCs, which I don't think I could do with the `pod` directive.

So for this use case to work, I think the k8s executor must able to create PVCs in addition to pods.

## Suggest implementation 

On my k8s cluster, if I wanted a pod with an extra volume for scratch storage, I would submit this:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-volume
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
--
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: ubuntu
    args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: /example-mount-path
      name: example-volume
  restartPolicy: Never
  volumes:
    - name: example-volume
      persistentVolumeClaim:
        claimName: example-volume
```

The user-defined properties are:
- the PVC name (`example-volume`)
- the access mode (`ReadWriteOnce`)
- the storage class (`rook-block`)
- the storage size (`20GiB`)

I think this example could be implemented either by the `pod volumeClaim` option or perhaps a separate `volume` directive:
```
# option 1
pod volumeClaim: "example-volume", storageClass: "rook-block", storage: "20gb"

# option 2
pod volumeClaim: "example-volume"
volume "example-volume", storageClass: "rook-block", storage: "20gb"
```

Either way, if the user specifies a volume in this way, nextflow should submit a PVC alongside the pod and then delete the PVC when the pod is deleted.

Like I said, this example is based on how I would create a PVC on my cluster, but it seems like a general solution to me. If users need other types of fields such as `volumeMode` and `volumeName`, they could be added as options just like `storageClass` and `storage`. And if we need more complexity than that... I suppose the user could just provide a PVC template instead? Are there any other major use cases for which `pod volumeClaim` is being used?
