### ISSUE TITLE
Support env / valueFrom in pod directive

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2352]
## New feature

The `pod` directive currently allows you to pass an environment variable in the form of a name/value pair:
```
# nextflow config
pod = [env: "MY_VAR", value: "MY_VALUE"]

# pod config
env:
  - name: MY_VAR
  - value: MY_VALUE
```

I am trying to pass pod information into the container itself via environment variable, using the following [example from the kubernetes documentation](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/):
```
env:
  - name: MY_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
```

So I would like to do this via the `pod` directive by providing a `valueFrom` instead of a `value`:
```
process {
    beforeScript = "echo \"#TRACE node_type=\${NODE_TYPE}\""

    pod = [
        env: "NODE_TYPE",
        valueFrom: [
            fieldRef: [
                fieldPath: "spec.nodeName"
            ]
        ]
    ]
}
```

This example is passing the node hostname into the pod, and the hostname is in turn saved to the execution log. I would use `$HOSTNAME` but it is set to the task name.

I would like the `pod` directive to recognize the `valueFrom` and pass it directly into the pod config, as I have shown in the example. Whereas `value` can be a string or secrect or configmap, `valueFrom` should be a map.
