### ISSUE TITLE
Add support for pod / affinity

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2390]
## New feature

The pod directive currently supports `nodeSelector` for selecting nodes by matching label. There is another property called `affinity` which allows for more complex matching, such as set logic (in, not in) and defining soft conditions:

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity

I propose we add support for the affinity object in the pod directive. It's easy to do because the PodOptions only needs to save the object as is:

```groovy
    @PackageScope void create(Map<String,String> entry) {
        if( entry.affinity ) {
            this.affinity = entry.affinity as Map
        }
        else if( entry.env && entry.value ) {
```

Here is an example I had to use today to avoid certain GPU nodes on my cluster:
```yaml
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: NotIn
            values: [T4]
```

And the pod directive I used:
```
pod = [
  affinity: [
    nodeAffinity: [
      requiredDuringSchedulingIgnoredDuringExecution: [
        nodeSelectorTerms: [
          [key: "gpu-type", operator: "NotIn", values: ["T4"]]
        ]
      ]
    ]
  ]
]
```

I patched Nextflow with this code and it works as intended.
