### ISSUE TITLE
Use `ephemeral-storage` for `disk` directive and `k8s` executor

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2986]
Nextflow currently supports the `cpus`, `memory`, `accelarator`, and `time` directives for allocating resources to k8s tasks. I think we can also support the `disk` directive by mapping it to the `ephemeral-storage` resource in k8s.

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage

Here is an example from the docs linked above:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
  volumes:
    - name: ephemeral
      emptyDir: {}
```

This feature would be a powerful way to provide local scratch storage to tasks:
```
process {
    disk 10.GB
    scratch = true // direct tasks to use the local storage
}
```

In order for this feature to work, I think we'll also need to support the `emptyDir` ephemeral volume, as shown in the above example. We can support it the same say we already support configMaps and secrets. `emptyDir` mounts the storage to the container, while `ephemeral-storage` specifies how much storage to provision.

(NOTE: emptyDir can also be backed by memory via `tmpfs`, in which case it is allocated via the `memory` resource instead of `ephemeral-storage`).

There is a PR (#1389) to add support for emptyDir but it is very old, so I will probably create a new PR that adds both `ephemeral-storage` and `emptyDir`.
