### ISSUE TITLE
Add pretty print option to `dump`

### ISSUE THREAD

**Issue by matthdsm** [nextflow-io/nextflow#3159]
## New feature

Hi,

Would it be possible to add a "pretty-print" option to the `dump` operator? This would greatly improve readability of large channel dumps

## Usage scenario 

Better readability when using nested maps in a channel

**Comment by mahesh-panchal** [comment]
Alternatively, make it suitable for streaming to `yq`, or preferably `jq`. 

Currently one can do:

`pretty_print_dump.nf`:
```nextflow
workflow {
    Channel.of( 
        [ 
            id: 'test', 
            samples: [ 
                [ id: 'S1', path: '/path/to/s1' ], 
                [ id: 'S2', path: '/path/to/s2' ], 
                [ id: 'S3', path: '/path/to/s3' ] 
            ] 
        ]
    ).dump(tag: 'map')
}
```
and then:
```bash
# pip install yq
nextflow run -dump-channels -ansi-log false pretty_print_dump.nf | grep "DUMP" | sed 's/.*\] \[/\[/' | yq  -y '.'
```
to produce:
```console
- id: test
- samples:
    - - id: S1
      - path: /path/to/s1
    - - id: S2
      - path: /path/to/s2
    - - id: S3
      - path: /path/to/s3
```

One can also hack this around to make it work on multiple dump lines by:
```bash
nextflow run -dump-channels -ansi-log false pretty_print_dump.nf | grep "DUMP" | sed 's/.*\] \[/\[/; a ---' | yq -y '.'
```
which gives:
```
- id: test
- samples:
    - - id: S1
      - path: /path/to/s1
    - - id: S2
      - path: /path/to/s2
    - - id: S3
      - path: /path/to/s3
---
- id: test
- samples:
    - - id: S1
      - path: /path/to/s1
    - - id: S2
      - path: /path/to/s2
    - - id: S3
      - path: /path/to/s3
--- null
...
```
( if you duplicate the channel entry in the script ).
