### ISSUE TITLE
Cannot use GCP c3-instances 

### ISSUE THREAD

**Issue by Puumanamana** [nextflow-io/nextflow#3885]
## Bug report 

For a given nextflow script running with a n1-standard-4 machineType, switching to a c3-instance with google-batch throws an error (null exit status)

### Expected behavior and actual behavior

Just being able to pick c3-instances

### Steps to reproduce the problem

main.nf
```nextflow
nextflow.enable.dsl = 2

process LS {
    machineType 'c3-standard-4'
    // machineType 'n1-standard-4'
    container 'ubuntu:latest'

    output:
    stdout

    script:
    """
    ls .
    """
}

workflow {
    LS()
}
```

nextflow.config
```nextflow
process.executor = "google-batch"

google {
    project = [GCP_PROJECT]
    region = "us-central1"
}

workDir = "gs://nxf-work/scratch/$USER/testing"
```

### Program output 

stdout
```
$ nextflow run main.nf
N E X T F L O W  ~  version 23.04.1
Launching `main.nf` [chaotic_jennings] DSL2 - revision: 300d479288
executor >  google-batch (1)
[25/3807d6] process > LS [100%] 1 of 1, failed: 1 ✘
ERROR ~ Error executing process > 'LS'

Caused by:
  Process `LS` terminated with an error exit status (null)

Command executed:

  ls .

Command exit status:
  null

Command output:
  (empty)

Work dir:
  gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

nextflow.log
```
Apr-19 18:16:22.267 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf
Apr-19 18:16:22.394 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.1
Apr-19 18:16:22.420 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/cedric/.nextflow/plugins; core-plugins: nf-amazon@1.16.2,nf-azure@1.0.1,nf-codecommit@0.1.4,nf-console@1.0.
5,nf-ga4gh@1.0.5,nf-google@1.7.3,nf-tower@1.5.12,nf-wave@0.8.2
Apr-19 18:16:22.433 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []                                                                                                                                                          Apr-19 18:16:22.434 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Apr-19 18:16:22.438 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Apr-19 18:16:22.454 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Apr-19 18:16:22.485 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/cedric/sandbox/troubleshoot/c3-instance/nextflow.config
Apr-19 18:16:22.486 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/cedric/sandbox/troubleshoot/c3-instance/nextflow.config
Apr-19 18:16:22.531 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Apr-19 18:16:23.656 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Apr-19 18:16:23.691 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [chaotic_jennings] DSL2 - revision: 300d479288
Apr-19 18:16:23.692 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[nf-google@1.7.3]
Apr-19 18:16:23.693 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[nf-google@1.7.3, nf-tower@1.5.12]
Apr-19 18:16:23.693 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-google version: 1.7.3
Apr-19 18:16:23.722 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-google@1.7.3' resolved
Apr-19 18:16:23.723 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-google@1.7.3'
Apr-19 18:16:23.833 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-google@1.7.3
Apr-19 18:16:23.833 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-tower version: 1.5.12
Apr-19 18:16:23.836 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-tower@1.5.12' resolved
Apr-19 18:16:23.836 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-tower@1.5.12'
Apr-19 18:16:23.857 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-tower@1.5.12
Apr-19 18:16:23.889 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /home/cedric/.nextflow/secrets/store.json
Apr-19 18:16:23.900 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@574a89e2] - activable => nextflow.secret.LocalSecretsProvider@574a89e2
Apr-19 18:16:24.092 [main] DEBUG nextflow.Session - Session UUID: 4d164ae8-c650-4459-a02d-49425f93c25c
Apr-19 18:16:24.093 [main] DEBUG nextflow.Session - Run name: chaotic_jennings
Apr-19 18:16:24.094 [main] DEBUG nextflow.Session - Executor pool size: 8
Apr-19 18:16:24.476 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=24; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Apr-19 18:16:24.542 [main] DEBUG nextflow.cli.CmdRun -
  Version: 23.04.1 build 5866
  Created: 15-04-2023 06:51 UTC
  System: Linux 5.15.0-1022-gcp
  Runtime: Groovy 3.0.16 on OpenJDK 64-Bit Server VM 11.0.17+8-post-Ubuntu-1ubuntu220.04
  Encoding: UTF-8 (UTF-8)
  Process: 1673720@nf-tower-main [10.128.0.2]
  CPUs: 8 - Mem: 62.8 GB (47.4 GB) - Swap: 0 (0)
Apr-19 18:16:24.598 [main] DEBUG nextflow.file.FileHelper - Can't check if specified path is NFS (1): gs://nxf-work/scratch/cedric/testing

Apr-19 18:16:24.599 [main] DEBUG nextflow.Session - Work-dir: gs://nxf-work/scratch/cedric/testing [null]
Apr-19 18:16:24.599 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/cedric/sandbox/troubleshoot/c3-instance/bin
Apr-19 18:16:24.646 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[GoogleLifeSciencesExecutor, GoogleBatchExecutor]                                                                                                 Apr-19 18:16:24.675 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Apr-19 18:16:24.681 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Apr-19 18:16:24.719 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Apr-19 18:16:24.740 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 9; maxThreads: 1000
Apr-19 18:16:24.867 [main] DEBUG nextflow.Session - Session start
Apr-19 18:16:25.253 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-19 18:16:25.357 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: google-batch
Apr-19 18:16:25.357 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'google-batch'
Apr-19 18:16:25.361 [main] DEBUG nextflow.executor.Executor - [warm up] executor > google-batch
Apr-19 18:16:25.370 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'google-batch' > capacity: 1000; pollInterval: 10s; dumpInterval: 5m
Apr-19 18:16:25.380 [main] DEBUG nextflow.cloud.google.GoogleOpts - Google auth via application DEFAULT
Apr-19 18:16:25.394 [main] DEBUG n.c.google.batch.GoogleBatchExecutor - [GOOGLE BATCH] Executor config=BatchConfig[googleOpts=GoogleOpts(projectId:rome-pipeline-engine, credsFile:null, location:null, enableRequesterPaysBuckets:false, credentials
:ComputeEngineCredentials{transportFactoryClassName=com.google.auth.oauth2.OAuth2Utils$DefaultHttpTransportFactory})
Apr-19 18:16:25.417 [main] DEBUG n.c.google.batch.client.BatchClient - [GOOGLE BATCH] Creating service client with config credentials
Apr-19 18:16:26.266 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: LS
Apr-19 18:16:26.267 [main] DEBUG nextflow.Session - Igniting dataflow network (1)
Apr-19 18:16:26.267 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > LS
Apr-19 18:16:26.269 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination
Apr-19 18:16:26.269 [main] DEBUG nextflow.Session - Session await
Apr-19 18:16:28.343 [Task submitter] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Cannot select machine type using cloud info for task: `LS` | Cannot access first() element from an empty List
Apr-19 18:16:29.487 [Task submitter] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] submitted > job=nf-253807d6-1681928186909; uid=nf-253807d6-168192-593fc925-55f5-407e0; work-dir=gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347
a17ae5fc9104f43b
Apr-19 18:16:29.487 [Task submitter] INFO  nextflow.Session - [25/3807d6] Submitted process > LS
Apr-19 18:16:35.454 [Task monitor] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Terminated job=nf-253807d6-1681928186909; state=FAILED
Apr-19 18:16:35.517 [Task monitor] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Cannot read exitstatus for task: `LS` | gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b/.exitcode
Apr-19 18:16:36.429 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: LS; status: COMPLETED; exit: null; error: -; workDir: gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b]
Apr-19 18:16:36.436 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=LS; work-dir=gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b
  error [nextflow.exception.ProcessFailedException]: Process `LS` terminated with an error exit status (null)
Apr-19 18:16:36.477 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b/.command.out
Apr-19 18:16:36.504 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b/.command.err
Apr-19 18:16:36.507 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'LS'

Caused by:
  Process `LS` terminated with an error exit status (null)

Command executed:

  ls .

Command exit status:
  null

Command output:
  (empty)

Work dir:
  gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Apr-19 18:16:36.520 [main] DEBUG nextflow.Session - Session await > all processes finished
Apr-19 18:16:36.548 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `LS` terminated with an error exit status (null)
Apr-19 18:16:36.594 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b/.command.err
Apr-19 18:16:36.628 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b/.command.out
Apr-19 18:16:36.630 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-19 18:16:36.656 [main] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b/.command.err
Apr-19 18:16:36.678 [main] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://nxf-work/scratch/cedric/testing/25/3807d64c7e4347a17ae5fc9104f43b/.command.out
Apr-19 18:16:36.685 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedC
ount=0; succeedDuration=0ms; failedDuration=977ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Apr-19 18:16:36.754 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Apr-19 18:16:36.754 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-tower@1.5.12'
Apr-19 18:16:36.754 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-tower
Apr-19 18:16:36.754 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-google@1.7.3'
Apr-19 18:16:36.754 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-google
Apr-19 18:16:36.781 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

### Environment 

* Nextflow version: 23.04.1
* Java version: openjdk version "11.0.17" 2022-10-18
* Operating system: Ubuntu 20.04.5 LTS
* Bash version: zsh 5.8 (x86_64-ubuntu-linux-gnu)

**Comment by pditommaso** [comment]
Is a valid instance type? it looks it fails to find it, see the warning `Cannot select machine type using cloud info for task` 

that's here 

https://github.com/nextflow-io/nextflow/blob/eda0845c15cd76f351396f2a27a305bb426a723a/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L420-L420

**Comment by pditommaso** [comment]
It looks so, this is the job description for a similar failure 


```
allocationPolicy:
  instances:
  - policy:
      machineType: c3-standard-4
      provisioningModel: SPOT
  labels:
    batch-job-id: nf-361b9a86-1681932459995
  location:
    allowedLocations:
    - regions/us-central1
    - zones/us-central1-a
    - zones/us-central1-b
    - zones/us-central1-c
    - zones/us-central1-f
  serviceAccount:
    email: 770252724889-compute@developer.gserviceaccount.com
createTime: '2023-04-19T19:27:42.752658307Z'
logsPolicy:
  destination: CLOUD_LOGGING
name: projects/my-nf-project-261815/locations/us-central1/jobs/nf-361b9a86-1681932459995
status:
  runDuration: 0s
  state: FAILED
  statusEvents:
  - description: Job state is set from QUEUED to FAILED for job projects/770252724889/locations/us-central1/jobs/nf-361b9a86-1681932459995.
    eventTime: '2023-04-19T19:27:48.142690465Z'
    type: STATUS_CHANGED
  - description: 'Job failed when checking quota limits: Batch Error: code - CODE_MACHINE_TYPE_NOT_FOUND,
      description - machine type c3-standard-4 for job nf-361b9a86-168193-8e616615-eaa2-40fb0,
      project 770252724889, region us-central1, zones (if any) us-central1-a,us-central1-b,us-central1-c,us-central1-f
      is not available.'
    eventTime: '2023-04-19T19:27:48.189347305Z'
    type: OPERATIONAL_INFO
taskGroups:
- name: projects/770252724889/locations/us-central1/jobs/nf-361b9a86-1681932459995/taskGroups/group0
  parallelism: '1'
  taskCount: '1'
  taskSpec:
    computeResource:
      cpuMilli: '1000'
      memoryMib: '2000'
    runnables:
    - container:
        commands:
        - /bin/bash
        - -o
        - pipefail
        - -c
        - trap "{ cp .command.log /mnt/disks/rnaseq-nf/scratch/36/1b9a867cc19a4739f6c76097ecdb3f/.command.log;
          }" ERR; /bin/bash /mnt/disks/rnaseq-nf/scratch/36/1b9a867cc19a4739f6c76097ecdb3f/.command.run
          2>&1 | tee .command.log
        imageUri: ubuntu:latest
        volumes:
        - /mnt/disks/rnaseq-nf/scratch/36/1b9a867cc19a4739f6c76097ecdb3f:/mnt/disks/rnaseq-nf/scratch/36/1b9a867cc19a4739f6c76097ecdb3f:rw
      environment: {}
    volumes:
    - gcs:
        remotePath: rnaseq-nf
      mountOptions:
      - -o rw,allow_other
      - -implicit-dirs
      mountPath: /mnt/disks/rnaseq-nf
uid: nf-361b9a86-168193-8e616615-eaa2-40fb0
updateTime: '2023-04-19T19:27:48.189347305Z'
```
