### ISSUE TITLE
Can't mount GCS bucket with requester-pays in GCP Batch

### ISSUE THREAD

**Issue by dpmccabe** [nextflow-io/nextflow#4780]
## Bug report 

If you have an input like `gs://the-bucket/file.bam` where `the-bucket` is set as requester-pays, GCSFuse fails to mount the volume in the Google Batch job.

### Expected behavior and actual behavior

The bucket should be mounted as a volume.

### Steps to reproduce the problem

Example config:

```
docker {
	enabled = true
}

google {
	enableRequesterPaysBuckets = true
	location = "us-central1"
	project = "..."

	batch {
		spot = false
		usePrivateAddress = false
		serviceAccountEmail = "...@....iam.gserviceaccount.com"
	}
}

process {
	executor = 'google-batch'
}

workDir = 'gs://.../work'
```

### Program output 

```
umount: /mnt/disks/the-bucket: not mounted.
Start gcsfuse/1.4.1 (Go version go1.21.5) for app "google-batch" using mount point: /mnt/disks/the-bucket
GCSFuse mount config flags: {"CreateEmptyFile":false,"Severity":"INFO","Format":"json","FilePath":"","LogRotateConfig":{"MaxFileSizeMB":512,"BackupFileCount":10,"Compress":true}}
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithStorageHandle: fs.NewServer: create file system: SetUpBucket: Error in iterating through objects: googleapi: Error 400: Bucket is a requester pays bucket but no user project provided., required
```

### Environment 

* Nextflow version: 23.10.1 build 5891
* Java version: Groovy 3.0.19 on OpenJDK 64-Bit Server VM 17.0.10+7
* Operating system: n/a
* Bash version: n/a

### Additional context

The problem can be worked around by adding `mountOptions` in a manual job submission:

```
    volumes:
    - gcs:
        remotePath: the-bucket
      mountOptions:
      - --billing-project my-project-id
      - -implicit-dirs
      - --app-name google-batch
      mountPath: /mnt/disks/the-bucket
```

I think [this line](https://github.com/nextflow-io/nextflow/blob/4debd56e4ee425d7d1766b9015ad14b2ed5b0a00/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchScriptLauncher.groovy#L137) would need to be updated to include the `google.project` config value.
