### ISSUE TITLE
Generate output schema from output definition

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#5213]
Spun off from #5103 

Nextflow should be able to generate an output schema from the workflow output definition, essentially as a list of index file schemas. See https://github.com/nf-core/fetchngs/pull/312 for a concrete example (`schema_outputs.yml`).

For now, the index file should specify a schema file (using fetchngs as example):
```groovy
output {
  'fastq' {
    index {
      path 'samplesheet.csv'
      schema 'assets/schema_samplesheet.yml'
    }
  }
}
```

This output definition would produce the following output schema:
```yaml
$schema: 'http://json-schema.org/draft-07/schema'
$id: 'https://raw.githubusercontent.com/nf-core/fetchngs/master/schema_outputs.yml'
title: 'nf-core/fetchngs pipeline outputs'
description: ''
type: object
properties:
  samplesheet:
    type: string
    format: file-path
    mimetype: text/csv
    schema: assets/schema_samplesheet.yml
```

Extra notes:
- Schema file should be JSON or YAML
- Can be extended in the future to define index schema in the DSL directly instead of referencing an external schema file
- Should be generated on each run or via some separate command.
- Should eventually be used with parameter schema for chaining pipelines.
