### ISSUE TITLE
Google Batch autoRetryExitCodes are not correctly set.

### ISSUE THREAD

**Issue by jorgee** [nextflow-io/nextflow#5827]
## Bug report 

The google.batch.autoRetryExitCodes set in the configuration it is not reflected in the Google Batch job description

### Expected behavior and actual behavior

When defining the google.batch.autoRetryExitCodes properties, they should appear in the Google Batch job description

### Steps to reproduce the problem

Set the following configuration
```
google {
    batch {
        autoRetryExitCodes = [50001, 50002, 50003, 50004, 50006]
        maxSpotAttempts = 5
    }
}
```
the look at the  job description
```
    lifecyclePolicies:
    - action: RETRY_TASK
      actionCondition:
        exitCodes:
        - 50001
    maxRetryCount: 5
```
The only exit code that is appearing is the default 50001.

### Environment 

* Nextflow version: 25.01-edge 
* Java version: 21
* Operating system: Linux
