### ISSUE TITLE
Repo config file for lint / format

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#5934]
Putting down some ideas for a potential new config file to be used by the new Nextflow `lint` and `format` commands.

Starting position:
* Can't use `nextflow.config` as separation of concerns, also potentially a bit recursive
* Want to make as generic as possible so it can be future-proofed (eg. not `.nextflowignore` to ignore files only, adaptable for more functionality)
* Common file format for easy interoperability

To make it clear what this is for, I'd suggest calling this thing `nextflowrc`, following the *nix convention with `rc` files for startup config / actions. It could be a hidden `.nextflowrc.*` dotfile or not, I could go either way.

With this, my initial stab is either YAML or TOML. Here's a very rough first draft with some suggestions for things that we may want to configure

`nextflowrc.yml`
```yaml
lint:
   exclude:
      - "testing/*"
      - "docs/**/*.nf"
   output-format: concise
format:
   exclude:
      - modules
   spaces: 4
   harshil-alignment: true
```

Or toml, as used by `pyproject.toml` and `netlify.toml` etc:

`nextflowrc.toml`
```toml
[lint]
exclude = ["myworkdir/*", "snippets/**/*.nf"]
output-format = "extended"

[format]
exclude = ["modules"]
tabs = true
harshil-alignment = false
```

Note that we _could_ support multiple formats, though I'm not sure that this would add much.

To avoid the proliferation of root-level config files, it may be possible for @nf-core to consider adopting this new file to replace `.nf-core.yml` (probably optionally), in an `nf-core` section in the file.

Thoughts + feedback welcome!
