### ISSUE TITLE
Improve support for GPU resources

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#997]
Related to #773 

I have a pipeline that uses GPUs. On my university's cluster, which uses PBS Pro, I can request GPUs in nextflow with `clusterOptions`. But now I'm trying to run my pipeline on a Kubernetes cluster and I don't see how to request a GPU from the nextflow script. What I would like in my pod config file is something like this:
```
        resources:
          limits:
            cpu: 4
            memory: "8Gi"
            nvidia.com/gpu: 1
```

I see that I can use `cpus` and `memory` for the first two, but what about the GPU resource? Could we expand the `pod` directive to also add custom resources like this? Something like `pod resource "nvidia.com/gpu" "1"`.

Alternatively, we could add a `gpu` directive. That should have some use for other executors (such as PBS). I just want to be able to use GPUs on a Kubernetes cluster from nextflow.
