### ISSUE TITLE
Support other volume schemes in k8s

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#998]
## New feature

I work on a Kubernetes cluster which does not have a storage resource that can be provisioned as a `ReadWriteMany` PV claim. However, there is a CephFS which is exposed as a Flexvolume. It's a shared filesystem which is persistent even across jobs, basically you request access as a user and then you are given a permanent allocation which you can use in pods and so on. So I think I should be able to run nextflow pipelines on this cluster using this shared storage, it's just not available as a PV claim. I have no experience in running a Kubernetes cluster so I don't know all of the details but I can at least describe what nextflow should generate in the pod configuration:

## Usage scenario 

A Kubernetes cluster has shared storage that is provided through other means aside from a PV claim.

## Suggest implementation 

So if you want to use a PV claim in a pod you would add this volume definition to your pod config:
```
  volumes:
    - name: example-volume
      persistentVolumeClaim:
        claimName: example-volume
```

For the shared storage that I can access, the volume definition looks like this:
```
  volumes:
  - name: fs-store
    flexVolume:
      driver: ceph.rook.io/rook
      fsType: ceph
      options:
        clusterNamespace: rook
        fsName: nautilusfs
        path: /<user-name>
        mountUser: <user-name>
        mountSecret: ceph-fs-secret
```

Where `<user-name>` is my username and `ceph-fs-secret` is a secret that I created, whose value is also tied to my username. So those two things would definitely have to be provided to nextflow. The other attributes are specific to this particular storage system and would probably have to be provided as well.

Do you think we could implement all of this through the `pod` directive? I figure as long as it has a valid volume definition, whether it's a PV claim or Flexvolume or something else, everything else should work.

**Comment by pditommaso** [comment]
I think this scenario should already be supported by NF in the extent your Flex volume is accessed through a PVC.

**Comment by bentsherman** [comment]
At present it does not, and I'm not sure how difficult it would be to provide the Flexvolume through a PVC. Right now I'm kind of caught in the middle of this problem because it could probably be solved from either side -- that is, either by nextflow or by the Kubernetes cluster -- but it isn't clear which way would be easier. If you could speak to how easy or difficult it would be to implement this feature that should help me figure out which side to bother more haha.

**Comment by pditommaso** [comment]
I don't think NF should take care to provision the storage, also because this should be under the realm of sysadmins. The PVC are meant exactly to decouple pods from the storage config, this is way is following this approach.

**Comment by bentsherman** [comment]
Excellent point! I think we've figured out how to make a PVC for this storage so I'll close this issue.

**Comment by anton-khodak** [comment]
Hi @bentsherman ! Would you mind sharing your Rook configuration for Nextflow? It would be of great help to other Rook adopters. I created a simple PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nf-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-block
```
The PV has been created and the volume is bound, but Nextflow times out on attaching to it. Probably, you have something different.

**Comment by bentsherman** [comment]
I actually had to have the sys admin create both the PV and PC for me because I didn't have the proper permissions. I don't have the original yaml but this is what I got from `kubectl`:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <name>
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: deepgtex-prp
```

For what it's worth, I think we used `storageClassName: manual` instead of `rook-ceph-block`.
